version: '3.8'

services:
  db:
    image: timescale/timescaledb-ha:pg17
    container_name: timescaledb
    restart: always
    command: postgres -c max_connections=100
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_INITDB_ARGS: '--auth-host=md5'
    ports:
      - '5432:5432'
    networks:
      - agent-network
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  google-assistant:
    image: samwang0723/mcp-google-assistant:latest
    environment:
      - SKIP_SSL_VERIFICATION=${SKIP_SSL_VERIFICATION}
    ports:
      - '3003:3000'
    networks:
      - agent-network

  time:
    image: samwang0723/mcp-time:latest
    environment:
      - TZ=Asia/Hong_Kong
    ports:
      - '3002:3000'
    networks:
      - agent-network

  booking:
    image: samwang0723/mcp-booking:latest
    environment:
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
      - DEFAULT_LATITUDE=${DEFAULT_LATITUDE}
      - DEFAULT_LONGITUDE=${DEFAULT_LONGITUDE}
      - DEFAULT_SEARCH_RADIUS=${DEFAULT_SEARCH_RADIUS}
    ports:
      - '3001:3000'
    networks:
      - agent-network

  web-search:
    image: samwang0723/mcp-brave:latest
    environment:
      - BRAVE_API_KEY=${BRAVE_API_KEY}
    ports:
      - '3004:3000'
    networks:
      - agent-network

  atlassian:
    image: samwang0723/mcp-atlassian:latest
    environment:
      - ATLASSIAN_HOST=${ATLASSIAN_HOST}
      - ATLASSIAN_EMAIL=${ATLASSIAN_EMAIL}
      - ATLASSIAN_API_TOKEN=${ATLASSIAN_API_TOKEN}
    ports:
      - '3005:3000'
    networks:
      - agent-network

  reddit:
    image: samwang0723/mcp-reddit:latest
    ports:
      - '3006:3000'
    networks:
      - agent-network

  perplexity:
    image: samwang0723/mcp-perplexity:latest
    environment:
      - PERPLEXITY_API_KEY=${PERPLEXITY_API_KEY}
    ports:
      - '3007:3000'
    networks:
      - agent-network

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    networks:
      - agent-network
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  db_data:
  redis_data:

networks:
  agent-network:
    driver: bridge
    name: agent-network
